language: node_js

branches:
  only:
  - master

matrix:
  include:

    #- os: linux
    #  dist: bionic

    - os: osx
      osx_image: xcode9.4
      before_install:
        - S="███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████"
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/miniconda.sh;
        - bash $HOME/miniconda.sh -b -p $HOME/miniconda;
        - export PATH="$HOME/miniconda/bin:$PATH";
        - conda config --set always_yes yes --set changeps1 no
        - echo -e "█$S\n"
        - source activate
        - pip install requests
        - echo -e "█$S\n" &&
          sudo pip install --upgrade youtube_dl
        - echo -e "█$S\n" &&
          youtube-dl --version
        - echo -e "█$S\n" &&
          npm install zerorpc

script:
  - S="███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████"
  - stty cols 200
  - echo -e "$S\n$S\n$S\n$S\n" &&
    echo $SHELL
  - echo -e "$S\n" &&
    echo $0
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo -e "$S\n" && ps -aef --forest; fi
  - echo -e "$S\n"
    && env
  - echo -e "$S\n$S\n$S\n$S\n"
  - export -f travis_wait travis_jigger
  - echo -e "$S\n"
  - . ./script.sh init
  - echo -e "$S\n"
  - ./script.sh run
  - echo -e "$S\n"
  - ./script.sh run2
