language: node_js

branches:
  only:
  - master
  - develop

matrix:
  include:

    - os: linux
      dist: bionic

script:
  - S="███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████"
  - stty cols 200
  - echo -e "$S\n$S\n$S\n$S\n" &&
    echo $SHELL
  - echo -e "$S\n" &&
    echo $0
  - echo -e "$S\n" &&
    ps -aef --forest
  - echo -e "$S\n"
    && env
  - echo -e "$S\n$S\n$S\n$S\n"
  - export -f travis_wait travis_jigger
  - echo -e "$S\n"
  - . ./script.sh init
  - echo -e "$S\n"
  - ./script.sh run
  - echo -e "$S\n"
  - ./script.sh run2
